/*
Copyright 2025 The KubeVirt Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	migrationcontrollerv1alpha1 "kubevirt.io/kubevirt-migration-controller/api/migrationcontroller/v1alpha1"
	scheme "kubevirt.io/kubevirt-migration-controller/pkg/client/clientset/versioned/scheme"
)

// MigMigrationsGetter has a method to return a MigMigrationInterface.
// A group's client should implement this interface.
type MigMigrationsGetter interface {
	MigMigrations(namespace string) MigMigrationInterface
}

// MigMigrationInterface has methods to work with MigMigration resources.
type MigMigrationInterface interface {
	Create(ctx context.Context, migMigration *migrationcontrollerv1alpha1.MigMigration, opts v1.CreateOptions) (*migrationcontrollerv1alpha1.MigMigration, error)
	Update(ctx context.Context, migMigration *migrationcontrollerv1alpha1.MigMigration, opts v1.UpdateOptions) (*migrationcontrollerv1alpha1.MigMigration, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, migMigration *migrationcontrollerv1alpha1.MigMigration, opts v1.UpdateOptions) (*migrationcontrollerv1alpha1.MigMigration, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*migrationcontrollerv1alpha1.MigMigration, error)
	List(ctx context.Context, opts v1.ListOptions) (*migrationcontrollerv1alpha1.MigMigrationList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *migrationcontrollerv1alpha1.MigMigration, err error)
	MigMigrationExpansion
}

// migMigrations implements MigMigrationInterface
type migMigrations struct {
	*gentype.ClientWithList[*migrationcontrollerv1alpha1.MigMigration, *migrationcontrollerv1alpha1.MigMigrationList]
}

// newMigMigrations returns a MigMigrations
func newMigMigrations(c *MigrationcontrollerV1alpha1Client, namespace string) *migMigrations {
	return &migMigrations{
		gentype.NewClientWithList[*migrationcontrollerv1alpha1.MigMigration, *migrationcontrollerv1alpha1.MigMigrationList](
			"migmigrations",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *migrationcontrollerv1alpha1.MigMigration { return &migrationcontrollerv1alpha1.MigMigration{} },
			func() *migrationcontrollerv1alpha1.MigMigrationList {
				return &migrationcontrollerv1alpha1.MigMigrationList{}
			},
		),
	}
}
