/*
Copyright 2025 The KubeVirt Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by client-gen. DO NOT EDIT.

package v1alpha1

import (
	context "context"

	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	gentype "k8s.io/client-go/gentype"
	migrations "kubevirt.io/kubevirt-migration-controller/api/migrationcontroller/v1alpha1"
	scheme "kubevirt.io/kubevirt-migration-controller/pkg/client/clientset/versioned/scheme"
)

// MigPlansGetter has a method to return a MigPlanInterface.
// A group's client should implement this interface.
type MigPlansGetter interface {
	MigPlans(namespace string) MigPlanInterface
}

// MigPlanInterface has methods to work with MigPlan resources.
type MigPlanInterface interface {
	Create(ctx context.Context, migPlan *migrations.MigPlan, opts v1.CreateOptions) (*migrations.MigPlan, error)
	Update(ctx context.Context, migPlan *migrations.MigPlan, opts v1.UpdateOptions) (*migrations.MigPlan, error)
	// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
	UpdateStatus(ctx context.Context, migPlan *migrations.MigPlan, opts v1.UpdateOptions) (*migrations.MigPlan, error)
	Delete(ctx context.Context, name string, opts v1.DeleteOptions) error
	DeleteCollection(ctx context.Context, opts v1.DeleteOptions, listOpts v1.ListOptions) error
	Get(ctx context.Context, name string, opts v1.GetOptions) (*migrations.MigPlan, error)
	List(ctx context.Context, opts v1.ListOptions) (*migrations.MigPlanList, error)
	Watch(ctx context.Context, opts v1.ListOptions) (watch.Interface, error)
	Patch(ctx context.Context, name string, pt types.PatchType, data []byte, opts v1.PatchOptions, subresources ...string) (result *migrations.MigPlan, err error)
	MigPlanExpansion
}

// migPlans implements MigPlanInterface
type migPlans struct {
	*gentype.ClientWithList[*migrations.MigPlan, *migrations.MigPlanList]
}

// newMigPlans returns a MigPlans
func newMigPlans(c *MigrationcontrollerV1alpha1Client, namespace string) *migPlans {
	return &migPlans{
		gentype.NewClientWithList[*migrations.MigPlan, *migrations.MigPlanList](
			"migplans",
			c.RESTClient(),
			scheme.ParameterCodec,
			namespace,
			func() *migrations.MigPlan { return &migrations.MigPlan{} },
			func() *migrations.MigPlanList { return &migrations.MigPlanList{} },
		),
	}
}
